//
//	ActivityIndicator.h
//	New Image
//
//	Created by Joe on 5/25/11
//	This code was generated by Opacity. You may use or modify it in any way.
//

#import <UIKit/UIKit.h>

extern const CGFloat kActivityIndicatorWidth;
extern const CGFloat kActivityIndicatorHeight;

@interface ActivityIndicator : UIView

@end
